version: '3.8'
services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env  # Defines variables based on platform architecture
    environment:
      - PLATFORM=local
      - STAGE=dev
      - CLOUD_ENDPOINT_OVERRIDE=http://localhost:4566
    volumes:
      - ${PWD}/:${PWD} # Paths has to match since we are starting containers from within the dev container when invoking lambda using SAM CLI
      - /var/run/docker.sock:/var/run/docker.sock
    command: sleep infinity
    network_mode: host


